#! /bin/bash
. functions
suUser=$sshUser
conf='nodes'
loadConfigure $conf


function doNode(){
	echo $1 $2 $suUser
	sshExec $sshUser $1 "su $suUser -c \"$2\""
}



function doAll(){
        for v in ${gHosts[@]}
        do
		doNode $v "$1"
        done
}

if [ $# -lt 1 ]
then
	echo 'Usage: ./doScp cmd <user>'
	echo ''
	exit
fi

if [ $# -eq 2 ]
then
	suUser=$2
fi

doAll "$1"

